### ISSUE TITLE
Version 3.1.0 is missing from Maven

### ISSUE THREAD

**Issue by boris-petrov** [sshtools/vfs#3]
Only [3.0.2](https://search.maven.org/artifact/com.sshtools/vfs-dropbox/3.0.2/jar) is there. Could you also upload 3.1.0 please?

P.S. This applies for all packages - Dropbox, GCS, Azure, etc.

**Comment by boris-petrov** [comment]
@ludup, @brett-smith - thank you for working on this project!

I see a version 3.1.0 is released in Maven Central. However, looking at the code, I can't seem to understand where development is done and what is released. There is the `master` branch which included my patches but then were reverted (why?). There is also the `develop` branch which also contains them (without being reverted). Both seem to contain commits for release-management. Can you explain a bit your process? It's an open-source project so it would be nice for people to know what they're using. :) Thanks!

**Comment by ludup** [comment]
It's pretty standard. 

master *should* contain the current release code. develop contains the next version in development, usually the next -SNAPSHOT. 

Your PRs were originally committed to master in error so reverted. They are part of the 3.2.0-SNAPSHOT which I hope to be will be finalising in the next couple of weeks.

**Comment by boris-petrov** [comment]
haha well, when it comes to open-source software, nothing is standard. :) But thanks for explaining what's going on. I'll eagerly await 3.2.0 then. Thank you!
